CREATE LOGIN Thomas WITH PASSWORD = 'Sc00bstheD00';
CREATE USER Thomas FROM LOGIN Thomas;
ALTER ROLE dbmanager ADD MEMBER Thomas;

CREATE LOGIN Todd WITH PASSWORD = '2dkZ69jwy6G8bML3';
CREATE USER Todd FROM LOGIN Todd;
ALTER ROLE dbmanager ADD MEMBER Todd;

CREATE LOGIN Emily WITH PASSWORD = 'MxgRKENd2Frvk8Nx';
CREATE USER Emily FROM LOGIN Emily;
ALTER ROLE dbmanager ADD MEMBER Emily;
